[project]
name = "redes"
version = "0.1.0"
description = "TP1"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "pytest",
    "pytest-cov>=6.1.1",
]

[tool.setuptools]
package-dir = {"" = "src"}

[tool.setuptools.packages.find]
where = ["src"]
